
export enum LiturgicalMoment {
    ENTRADA = "ENTRADA",
    ATO_PENITENCIAL = "ATO_PENITENCIAL",
    GLORIA = "GLORIA",
    SALMO = "SALMO",
    ACLAMACAO = "ACLAMACAO",
    OFERTORIO = "OFERTORIO",
    SANTO = "SANTO",
    COMUNHAO = "COMUNHAO",
    ACAO_DE_GRACAS = "ACAO_DE_GRACAS",
    FINAL = "FINAL",
    ADORACAO = "ADORACAO",
    ASPERSAO = "ASPERSAO",
    BAPTISMO = "BAPTISMO",
    BENCAO_DAS_ALIANCAS = "BENCAO_DAS_ALIANCAS",
    CORDEIRO_DE_DEUS = "CORDEIRO_DE_DEUS",
    CRISMA = "CRISMA",
    INTRODUCAO_DA_PALAVRA = "INTRODUCAO_DA_PALAVRA",
    LOUVOR = "LOUVOR",
    PAI_NOSSO = "PAI_NOSSO",
    REFLEXAO = "REFLEXAO",
    TERCO_MISTERIO = "TERCO_MISTERIO",
  }
  
  export enum Instrument {
    ORGAO = "ORGAO",
    GUITARRA = "GUITARRA",
    PIANO = "PIANO",
    CORO = "CORO",
    OUTRO = "OUTRO",
  }
  
  export enum SongType {
    ACORDES = "ACORDES",
    PARTITURA = "PARTITURA",
  }
  
  export enum SourceType {
    PDF = "PDF",
    MARKDOWN = "MARKDOWN",
  }
  